Repository pycontribs/enrich, pull requests merged in 2022-12, with the labels that each got.

#45 Update build-system requirement for setuptools-scm to >=7.0.0
  pyproject.toml
  setup.cfg
  setup.py
Labels: bug

#46 Remove mock from test dependencies
  setup.cfg
Labels: bug

#52 Update CODEOWNERS
  .github/CODEOWNERS
Labels: skip-changelog

#54 Fix typo: cosole -> console (codespell)
  README.md
Labels: skip-changelog

#56 Move tests outside package
  setup.cfg
  test/__init__.py
  test/test_console.py
  test/test_logging.py
Labels: bug, skip-changelog

#57 Adopt PEP-621
  .flake8
  .github/workflows/release.yml
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  MANIFEST.in
  mypy.ini
  pyproject.toml
  setup.cfg
  setup.py
Labels: bug
