Repository pycontribs/enrich, pull requests merged in 2024-06, with the labels that each got.

#62 RichHandler add omit_repeated_times parameter
  pyproject.toml
  src/enrich/logging.py
Labels: bug

#64 GHA reusable action renames
  .github/release-drafter.yml
  .github/workflows/ack.yml
  .github/workflows/push.yml
Labels: skip-changelog

#65 Externalize package requirments
  .config/requirements-test.in
  .config/requirements.in
  .gitignore
  pyproject.toml
Labels: bug

#67 Require python 3.9 or newer
  .github/workflows/release.yml
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  pyproject.toml
  src/enrich/__init__.py
  src/enrich/console.py
  src/enrich/logging.py
  test/test_console.py
  test/test_logging.py
Labels: enhancement
